/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WarehousePrototypeRouteImport } from './routes/warehouse-prototype'
import { Route as TicketsRouteImport } from './routes/tickets'
import { Route as TeamsRouteImport } from './routes/teams'
import { Route as SupportFaqRouteImport } from './routes/support-faq'
import { Route as ServiceContractsRouteImport } from './routes/service-contracts'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as SalesOrdersRouteImport } from './routes/sales-orders'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as QuyTrinhQuanLyKhoRouteImport } from './routes/quy-trinh-quan-ly-kho'
import { Route as QuotesRouteImport } from './routes/quotes'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ProjectTasksRouteImport } from './routes/project-tasks'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as OrganizationsRouteImport } from './routes/organizations'
import { Route as OpportunitiesRouteImport } from './routes/opportunities'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as ActivitiesRouteImport } from './routes/activities'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WarehousesIndexRouteImport } from './routes/warehouses.index'
import { Route as LeadsIndexRouteImport } from './routes/leads.index'
import { Route as WarehousesWarehouseIdRouteImport } from './routes/warehouses.$warehouseId'
import { Route as TicketsTicketIdRouteImport } from './routes/tickets.$ticketId'
import { Route as SalesOrdersOrderIdRouteImport } from './routes/sales-orders.$orderId'
import { Route as QuotesQuoteIdRouteImport } from './routes/quotes.$quoteId'
import { Route as OrganizationsOrgIdRouteImport } from './routes/organizations.$orgId'
import { Route as OpportunitiesOppIdRouteImport } from './routes/opportunities.$oppId'
import { Route as LeadsCreateRouteImport } from './routes/leads.create'
import { Route as LeadsLeadIdRouteImport } from './routes/leads.$leadId'
import { Route as InventoryStorageRouteImport } from './routes/inventory.storage'
import { Route as InventoryOutboundRouteImport } from './routes/inventory.outbound'
import { Route as InventoryInboundRouteImport } from './routes/inventory.inbound'

const WarehousePrototypeRoute = WarehousePrototypeRouteImport.update({
  id: '/warehouse-prototype',
  path: '/warehouse-prototype',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsRoute = TicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsRoute = TeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportFaqRoute = SupportFaqRouteImport.update({
  id: '/support-faq',
  path: '/support-faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceContractsRoute = ServiceContractsRouteImport.update({
  id: '/service-contracts',
  path: '/service-contracts',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesOrdersRoute = SalesOrdersRouteImport.update({
  id: '/sales-orders',
  path: '/sales-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const QuyTrinhQuanLyKhoRoute = QuyTrinhQuanLyKhoRouteImport.update({
  id: '/quy-trinh-quan-ly-kho',
  path: '/quy-trinh-quan-ly-kho',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotesRoute = QuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectTasksRoute = ProjectTasksRouteImport.update({
  id: '/project-tasks',
  path: '/project-tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsRoute = OrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesRoute = OpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesRoute = ActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WarehousesIndexRoute = WarehousesIndexRouteImport.update({
  id: '/warehouses/',
  path: '/warehouses/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsIndexRoute = LeadsIndexRouteImport.update({
  id: '/leads/',
  path: '/leads/',
  getParentRoute: () => rootRouteImport,
} as any)
const WarehousesWarehouseIdRoute = WarehousesWarehouseIdRouteImport.update({
  id: '/warehouses/$warehouseId',
  path: '/warehouses/$warehouseId',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsTicketIdRoute = TicketsTicketIdRouteImport.update({
  id: '/$ticketId',
  path: '/$ticketId',
  getParentRoute: () => TicketsRoute,
} as any)
const SalesOrdersOrderIdRoute = SalesOrdersOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => SalesOrdersRoute,
} as any)
const QuotesQuoteIdRoute = QuotesQuoteIdRouteImport.update({
  id: '/$quoteId',
  path: '/$quoteId',
  getParentRoute: () => QuotesRoute,
} as any)
const OrganizationsOrgIdRoute = OrganizationsOrgIdRouteImport.update({
  id: '/$orgId',
  path: '/$orgId',
  getParentRoute: () => OrganizationsRoute,
} as any)
const OpportunitiesOppIdRoute = OpportunitiesOppIdRouteImport.update({
  id: '/$oppId',
  path: '/$oppId',
  getParentRoute: () => OpportunitiesRoute,
} as any)
const LeadsCreateRoute = LeadsCreateRouteImport.update({
  id: '/leads/create',
  path: '/leads/create',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsLeadIdRoute = LeadsLeadIdRouteImport.update({
  id: '/leads/$leadId',
  path: '/leads/$leadId',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryStorageRoute = InventoryStorageRouteImport.update({
  id: '/inventory/storage',
  path: '/inventory/storage',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryOutboundRoute = InventoryOutboundRouteImport.update({
  id: '/inventory/outbound',
  path: '/inventory/outbound',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryInboundRoute = InventoryInboundRouteImport.update({
  id: '/inventory/inbound',
  path: '/inventory/inbound',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/calendar': typeof CalendarRoute
  '/contacts': typeof ContactsRoute
  '/documents': typeof DocumentsRoute
  '/opportunities': typeof OpportunitiesRouteWithChildren
  '/organizations': typeof OrganizationsRouteWithChildren
  '/products': typeof ProductsRoute
  '/project-tasks': typeof ProjectTasksRoute
  '/projects': typeof ProjectsRoute
  '/quotes': typeof QuotesRouteWithChildren
  '/quy-trinh-quan-ly-kho': typeof QuyTrinhQuanLyKhoRoute
  '/reports': typeof ReportsRoute
  '/rules': typeof RulesRoute
  '/sales-orders': typeof SalesOrdersRouteWithChildren
  '/schedule': typeof ScheduleRoute
  '/service-contracts': typeof ServiceContractsRoute
  '/support-faq': typeof SupportFaqRoute
  '/teams': typeof TeamsRoute
  '/tickets': typeof TicketsRouteWithChildren
  '/warehouse-prototype': typeof WarehousePrototypeRoute
  '/inventory/inbound': typeof InventoryInboundRoute
  '/inventory/outbound': typeof InventoryOutboundRoute
  '/inventory/storage': typeof InventoryStorageRoute
  '/leads/$leadId': typeof LeadsLeadIdRoute
  '/leads/create': typeof LeadsCreateRoute
  '/opportunities/$oppId': typeof OpportunitiesOppIdRoute
  '/organizations/$orgId': typeof OrganizationsOrgIdRoute
  '/quotes/$quoteId': typeof QuotesQuoteIdRoute
  '/sales-orders/$orderId': typeof SalesOrdersOrderIdRoute
  '/tickets/$ticketId': typeof TicketsTicketIdRoute
  '/warehouses/$warehouseId': typeof WarehousesWarehouseIdRoute
  '/leads/': typeof LeadsIndexRoute
  '/warehouses/': typeof WarehousesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/calendar': typeof CalendarRoute
  '/contacts': typeof ContactsRoute
  '/documents': typeof DocumentsRoute
  '/opportunities': typeof OpportunitiesRouteWithChildren
  '/organizations': typeof OrganizationsRouteWithChildren
  '/products': typeof ProductsRoute
  '/project-tasks': typeof ProjectTasksRoute
  '/projects': typeof ProjectsRoute
  '/quotes': typeof QuotesRouteWithChildren
  '/quy-trinh-quan-ly-kho': typeof QuyTrinhQuanLyKhoRoute
  '/reports': typeof ReportsRoute
  '/rules': typeof RulesRoute
  '/sales-orders': typeof SalesOrdersRouteWithChildren
  '/schedule': typeof ScheduleRoute
  '/service-contracts': typeof ServiceContractsRoute
  '/support-faq': typeof SupportFaqRoute
  '/teams': typeof TeamsRoute
  '/tickets': typeof TicketsRouteWithChildren
  '/warehouse-prototype': typeof WarehousePrototypeRoute
  '/inventory/inbound': typeof InventoryInboundRoute
  '/inventory/outbound': typeof InventoryOutboundRoute
  '/inventory/storage': typeof InventoryStorageRoute
  '/leads/$leadId': typeof LeadsLeadIdRoute
  '/leads/create': typeof LeadsCreateRoute
  '/opportunities/$oppId': typeof OpportunitiesOppIdRoute
  '/organizations/$orgId': typeof OrganizationsOrgIdRoute
  '/quotes/$quoteId': typeof QuotesQuoteIdRoute
  '/sales-orders/$orderId': typeof SalesOrdersOrderIdRoute
  '/tickets/$ticketId': typeof TicketsTicketIdRoute
  '/warehouses/$warehouseId': typeof WarehousesWarehouseIdRoute
  '/leads': typeof LeadsIndexRoute
  '/warehouses': typeof WarehousesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/calendar': typeof CalendarRoute
  '/contacts': typeof ContactsRoute
  '/documents': typeof DocumentsRoute
  '/opportunities': typeof OpportunitiesRouteWithChildren
  '/organizations': typeof OrganizationsRouteWithChildren
  '/products': typeof ProductsRoute
  '/project-tasks': typeof ProjectTasksRoute
  '/projects': typeof ProjectsRoute
  '/quotes': typeof QuotesRouteWithChildren
  '/quy-trinh-quan-ly-kho': typeof QuyTrinhQuanLyKhoRoute
  '/reports': typeof ReportsRoute
  '/rules': typeof RulesRoute
  '/sales-orders': typeof SalesOrdersRouteWithChildren
  '/schedule': typeof ScheduleRoute
  '/service-contracts': typeof ServiceContractsRoute
  '/support-faq': typeof SupportFaqRoute
  '/teams': typeof TeamsRoute
  '/tickets': typeof TicketsRouteWithChildren
  '/warehouse-prototype': typeof WarehousePrototypeRoute
  '/inventory/inbound': typeof InventoryInboundRoute
  '/inventory/outbound': typeof InventoryOutboundRoute
  '/inventory/storage': typeof InventoryStorageRoute
  '/leads/$leadId': typeof LeadsLeadIdRoute
  '/leads/create': typeof LeadsCreateRoute
  '/opportunities/$oppId': typeof OpportunitiesOppIdRoute
  '/organizations/$orgId': typeof OrganizationsOrgIdRoute
  '/quotes/$quoteId': typeof QuotesQuoteIdRoute
  '/sales-orders/$orderId': typeof SalesOrdersOrderIdRoute
  '/tickets/$ticketId': typeof TicketsTicketIdRoute
  '/warehouses/$warehouseId': typeof WarehousesWarehouseIdRoute
  '/leads/': typeof LeadsIndexRoute
  '/warehouses/': typeof WarehousesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activities'
    | '/calendar'
    | '/contacts'
    | '/documents'
    | '/opportunities'
    | '/organizations'
    | '/products'
    | '/project-tasks'
    | '/projects'
    | '/quotes'
    | '/quy-trinh-quan-ly-kho'
    | '/reports'
    | '/rules'
    | '/sales-orders'
    | '/schedule'
    | '/service-contracts'
    | '/support-faq'
    | '/teams'
    | '/tickets'
    | '/warehouse-prototype'
    | '/inventory/inbound'
    | '/inventory/outbound'
    | '/inventory/storage'
    | '/leads/$leadId'
    | '/leads/create'
    | '/opportunities/$oppId'
    | '/organizations/$orgId'
    | '/quotes/$quoteId'
    | '/sales-orders/$orderId'
    | '/tickets/$ticketId'
    | '/warehouses/$warehouseId'
    | '/leads/'
    | '/warehouses/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activities'
    | '/calendar'
    | '/contacts'
    | '/documents'
    | '/opportunities'
    | '/organizations'
    | '/products'
    | '/project-tasks'
    | '/projects'
    | '/quotes'
    | '/quy-trinh-quan-ly-kho'
    | '/reports'
    | '/rules'
    | '/sales-orders'
    | '/schedule'
    | '/service-contracts'
    | '/support-faq'
    | '/teams'
    | '/tickets'
    | '/warehouse-prototype'
    | '/inventory/inbound'
    | '/inventory/outbound'
    | '/inventory/storage'
    | '/leads/$leadId'
    | '/leads/create'
    | '/opportunities/$oppId'
    | '/organizations/$orgId'
    | '/quotes/$quoteId'
    | '/sales-orders/$orderId'
    | '/tickets/$ticketId'
    | '/warehouses/$warehouseId'
    | '/leads'
    | '/warehouses'
  id:
    | '__root__'
    | '/'
    | '/activities'
    | '/calendar'
    | '/contacts'
    | '/documents'
    | '/opportunities'
    | '/organizations'
    | '/products'
    | '/project-tasks'
    | '/projects'
    | '/quotes'
    | '/quy-trinh-quan-ly-kho'
    | '/reports'
    | '/rules'
    | '/sales-orders'
    | '/schedule'
    | '/service-contracts'
    | '/support-faq'
    | '/teams'
    | '/tickets'
    | '/warehouse-prototype'
    | '/inventory/inbound'
    | '/inventory/outbound'
    | '/inventory/storage'
    | '/leads/$leadId'
    | '/leads/create'
    | '/opportunities/$oppId'
    | '/organizations/$orgId'
    | '/quotes/$quoteId'
    | '/sales-orders/$orderId'
    | '/tickets/$ticketId'
    | '/warehouses/$warehouseId'
    | '/leads/'
    | '/warehouses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivitiesRoute: typeof ActivitiesRoute
  CalendarRoute: typeof CalendarRoute
  ContactsRoute: typeof ContactsRoute
  DocumentsRoute: typeof DocumentsRoute
  OpportunitiesRoute: typeof OpportunitiesRouteWithChildren
  OrganizationsRoute: typeof OrganizationsRouteWithChildren
  ProductsRoute: typeof ProductsRoute
  ProjectTasksRoute: typeof ProjectTasksRoute
  ProjectsRoute: typeof ProjectsRoute
  QuotesRoute: typeof QuotesRouteWithChildren
  QuyTrinhQuanLyKhoRoute: typeof QuyTrinhQuanLyKhoRoute
  ReportsRoute: typeof ReportsRoute
  RulesRoute: typeof RulesRoute
  SalesOrdersRoute: typeof SalesOrdersRouteWithChildren
  ScheduleRoute: typeof ScheduleRoute
  ServiceContractsRoute: typeof ServiceContractsRoute
  SupportFaqRoute: typeof SupportFaqRoute
  TeamsRoute: typeof TeamsRoute
  TicketsRoute: typeof TicketsRouteWithChildren
  WarehousePrototypeRoute: typeof WarehousePrototypeRoute
  InventoryInboundRoute: typeof InventoryInboundRoute
  InventoryOutboundRoute: typeof InventoryOutboundRoute
  InventoryStorageRoute: typeof InventoryStorageRoute
  LeadsLeadIdRoute: typeof LeadsLeadIdRoute
  LeadsCreateRoute: typeof LeadsCreateRoute
  WarehousesWarehouseIdRoute: typeof WarehousesWarehouseIdRoute
  LeadsIndexRoute: typeof LeadsIndexRoute
  WarehousesIndexRoute: typeof WarehousesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/warehouse-prototype': {
      id: '/warehouse-prototype'
      path: '/warehouse-prototype'
      fullPath: '/warehouse-prototype'
      preLoaderRoute: typeof WarehousePrototypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets': {
      id: '/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof TicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support-faq': {
      id: '/support-faq'
      path: '/support-faq'
      fullPath: '/support-faq'
      preLoaderRoute: typeof SupportFaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-contracts': {
      id: '/service-contracts'
      path: '/service-contracts'
      fullPath: '/service-contracts'
      preLoaderRoute: typeof ServiceContractsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales-orders': {
      id: '/sales-orders'
      path: '/sales-orders'
      fullPath: '/sales-orders'
      preLoaderRoute: typeof SalesOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quy-trinh-quan-ly-kho': {
      id: '/quy-trinh-quan-ly-kho'
      path: '/quy-trinh-quan-ly-kho'
      fullPath: '/quy-trinh-quan-ly-kho'
      preLoaderRoute: typeof QuyTrinhQuanLyKhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotes': {
      id: '/quotes'
      path: '/quotes'
      fullPath: '/quotes'
      preLoaderRoute: typeof QuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project-tasks': {
      id: '/project-tasks'
      path: '/project-tasks'
      fullPath: '/project-tasks'
      preLoaderRoute: typeof ProjectTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations': {
      id: '/organizations'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof OrganizationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities': {
      id: '/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof OpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities': {
      id: '/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof ActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warehouses/': {
      id: '/warehouses/'
      path: '/warehouses'
      fullPath: '/warehouses/'
      preLoaderRoute: typeof WarehousesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads/': {
      id: '/leads/'
      path: '/leads'
      fullPath: '/leads/'
      preLoaderRoute: typeof LeadsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warehouses/$warehouseId': {
      id: '/warehouses/$warehouseId'
      path: '/warehouses/$warehouseId'
      fullPath: '/warehouses/$warehouseId'
      preLoaderRoute: typeof WarehousesWarehouseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets/$ticketId': {
      id: '/tickets/$ticketId'
      path: '/$ticketId'
      fullPath: '/tickets/$ticketId'
      preLoaderRoute: typeof TicketsTicketIdRouteImport
      parentRoute: typeof TicketsRoute
    }
    '/sales-orders/$orderId': {
      id: '/sales-orders/$orderId'
      path: '/$orderId'
      fullPath: '/sales-orders/$orderId'
      preLoaderRoute: typeof SalesOrdersOrderIdRouteImport
      parentRoute: typeof SalesOrdersRoute
    }
    '/quotes/$quoteId': {
      id: '/quotes/$quoteId'
      path: '/$quoteId'
      fullPath: '/quotes/$quoteId'
      preLoaderRoute: typeof QuotesQuoteIdRouteImport
      parentRoute: typeof QuotesRoute
    }
    '/organizations/$orgId': {
      id: '/organizations/$orgId'
      path: '/$orgId'
      fullPath: '/organizations/$orgId'
      preLoaderRoute: typeof OrganizationsOrgIdRouteImport
      parentRoute: typeof OrganizationsRoute
    }
    '/opportunities/$oppId': {
      id: '/opportunities/$oppId'
      path: '/$oppId'
      fullPath: '/opportunities/$oppId'
      preLoaderRoute: typeof OpportunitiesOppIdRouteImport
      parentRoute: typeof OpportunitiesRoute
    }
    '/leads/create': {
      id: '/leads/create'
      path: '/leads/create'
      fullPath: '/leads/create'
      preLoaderRoute: typeof LeadsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads/$leadId': {
      id: '/leads/$leadId'
      path: '/leads/$leadId'
      fullPath: '/leads/$leadId'
      preLoaderRoute: typeof LeadsLeadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/storage': {
      id: '/inventory/storage'
      path: '/inventory/storage'
      fullPath: '/inventory/storage'
      preLoaderRoute: typeof InventoryStorageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/outbound': {
      id: '/inventory/outbound'
      path: '/inventory/outbound'
      fullPath: '/inventory/outbound'
      preLoaderRoute: typeof InventoryOutboundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/inbound': {
      id: '/inventory/inbound'
      path: '/inventory/inbound'
      fullPath: '/inventory/inbound'
      preLoaderRoute: typeof InventoryInboundRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface OpportunitiesRouteChildren {
  OpportunitiesOppIdRoute: typeof OpportunitiesOppIdRoute
}

const OpportunitiesRouteChildren: OpportunitiesRouteChildren = {
  OpportunitiesOppIdRoute: OpportunitiesOppIdRoute,
}

const OpportunitiesRouteWithChildren = OpportunitiesRoute._addFileChildren(
  OpportunitiesRouteChildren,
)

interface OrganizationsRouteChildren {
  OrganizationsOrgIdRoute: typeof OrganizationsOrgIdRoute
}

const OrganizationsRouteChildren: OrganizationsRouteChildren = {
  OrganizationsOrgIdRoute: OrganizationsOrgIdRoute,
}

const OrganizationsRouteWithChildren = OrganizationsRoute._addFileChildren(
  OrganizationsRouteChildren,
)

interface QuotesRouteChildren {
  QuotesQuoteIdRoute: typeof QuotesQuoteIdRoute
}

const QuotesRouteChildren: QuotesRouteChildren = {
  QuotesQuoteIdRoute: QuotesQuoteIdRoute,
}

const QuotesRouteWithChildren =
  QuotesRoute._addFileChildren(QuotesRouteChildren)

interface SalesOrdersRouteChildren {
  SalesOrdersOrderIdRoute: typeof SalesOrdersOrderIdRoute
}

const SalesOrdersRouteChildren: SalesOrdersRouteChildren = {
  SalesOrdersOrderIdRoute: SalesOrdersOrderIdRoute,
}

const SalesOrdersRouteWithChildren = SalesOrdersRoute._addFileChildren(
  SalesOrdersRouteChildren,
)

interface TicketsRouteChildren {
  TicketsTicketIdRoute: typeof TicketsTicketIdRoute
}

const TicketsRouteChildren: TicketsRouteChildren = {
  TicketsTicketIdRoute: TicketsTicketIdRoute,
}

const TicketsRouteWithChildren =
  TicketsRoute._addFileChildren(TicketsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivitiesRoute: ActivitiesRoute,
  CalendarRoute: CalendarRoute,
  ContactsRoute: ContactsRoute,
  DocumentsRoute: DocumentsRoute,
  OpportunitiesRoute: OpportunitiesRouteWithChildren,
  OrganizationsRoute: OrganizationsRouteWithChildren,
  ProductsRoute: ProductsRoute,
  ProjectTasksRoute: ProjectTasksRoute,
  ProjectsRoute: ProjectsRoute,
  QuotesRoute: QuotesRouteWithChildren,
  QuyTrinhQuanLyKhoRoute: QuyTrinhQuanLyKhoRoute,
  ReportsRoute: ReportsRoute,
  RulesRoute: RulesRoute,
  SalesOrdersRoute: SalesOrdersRouteWithChildren,
  ScheduleRoute: ScheduleRoute,
  ServiceContractsRoute: ServiceContractsRoute,
  SupportFaqRoute: SupportFaqRoute,
  TeamsRoute: TeamsRoute,
  TicketsRoute: TicketsRouteWithChildren,
  WarehousePrototypeRoute: WarehousePrototypeRoute,
  InventoryInboundRoute: InventoryInboundRoute,
  InventoryOutboundRoute: InventoryOutboundRoute,
  InventoryStorageRoute: InventoryStorageRoute,
  LeadsLeadIdRoute: LeadsLeadIdRoute,
  LeadsCreateRoute: LeadsCreateRoute,
  WarehousesWarehouseIdRoute: WarehousesWarehouseIdRoute,
  LeadsIndexRoute: LeadsIndexRoute,
  WarehousesIndexRoute: WarehousesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
